### PR TITLE
Fix reports link step sort for numeric 

### LINKED ISSUE #761: Sorting in reports with link steps doesn't work as expected
When sorting a table which is showing a link step, the sort seems to order numbers based on text sorting rules, not on number sorting rules.

See the column `bb n1`; the values are numeric but the descending order was done using character order.

Image

### PR DESCRIPTION
**Pull request by KinyaElGrande**
Fixes https://github.com/cortezaproject/corteza/issues/761
 
**Issue**: When sorting a table showing a link step, the sort seems to order numbers based on text sorting rules, not number sorting rules.

### CODE REVIEW

**Review by petergrlica — APPROVED** [review]
lgtm

**Comment by manuelnelson** [comment]
@KinyaElGrande This still seems to be happening?  I've confirmed that the "Days Since Needs Assessment" is a Number field, so I'm not sure why it's sorting like the image below? Let me know if there's an extra step I need to take to get the sorting to work on the number field.

image

**Comment by KinyaElGrande** [comment]
@manuelnelson  Thank you for reporting this issue.
I'll work on reproducing it, then formally open an issue for it after I confirm the behaviour.

Could you please provide the version of Corteza you're running on.

**Comment by KinyaElGrande** [comment]
@manuelnelson,
I have tried reproducing this issue on Corteza `2024.9.3` and everything appears to be working as expected as shown in the GIF below.

Could you please double-check your Corteza version? It might be older than the version where this was fixed.

ScreenRecording2025-06-20at12 51 53-ezgif com-video-to-gif-converter

**Comment by KinyaElGrande** [comment]
I have tried reproducing this issue on Corteza `2024.9.3 ` and everything appears to be working as expected, as shown in the GIF below.
Could you please double-check your Corteza version? It might be older than the version where this was fixed.

ScreenRecording2025-06-20at14 08 08-ezgif com-video-to-gif-converter

**Pull request merged**
