### PR TITLE
Fix geometry module field map if one coordinate is missing

### LINKED ISSUE #1032: Add a validator for geo field if one set of coordinates is missing
## Description of the bug

When adding new records for geometry and clicking on the map icon, it only shows a blank gray space instead of a map. However, if I manually put in numbers for longitude and latitude, it will show the map. 

Image

## Reproduction steps

It looks like when you enter coordinates just for the longitude and you miss out the latitude the map will be grayed out. So probably we should add a validator if one of each is missing to throw some notification/error.

## Expected behavior 

_Map of the world should be populated_

## Screenshot/Video

Image

## Version

Branch: 2023.3.0-dev.5.1
Reporter: Iveta (Test Fest)
Browser: Safari

### PR DESCRIPTION
**Pull request by kelanik8**
# The following changes are implemented
TODO: Summary

# Changes in the user interface:
TODO: Add screenshots, recordings or remove this section

# Checklist when submitting a final (!draft) PR
 - [ ] Commits are tidied up, squashed if needed and follow guidelines in CONTRIBUTING.md
 - [ ] Code builds
 - [ ] All existing tests pass
 - [ ] All new critical code is covered by tests
 - [ ] PR is linked to the relevant issue(s)
 - [ ] Rebased with the target branch

### CODE REVIEW

**Review by Fajfa — CHANGES_REQUESTED** [review]
Should a similar thing be done in geometry viewer?

**Review by Fajfa — APPROVED** [review]

**Comment by katrinDY** [comment]
- issue when adding latitude
https://github.com/cortezaproject/corteza/assets/85161724/bb231df3-0de4-46ca-8725-673b8d20ae4a

- the errors
Screenshot 2023-06-20 at 11 44 49

- warnings ins vs code
Screenshot 2023-06-20 at 11 47 58

**Comment by katrinDY** [comment]
LGTM

**Comment by katrinDY** [comment]
Tested the maps in all webapps. LGTM

**Pull request merged**
